#!/usr/bin/env python3
#
# File: whaemoji_gen.py
# Auth: Joe Broesele
# Mod.: Joe Broesele
# Date: 18 May 2020
# Rev.: 19 May 2020
#
# Automatically generate the file './libs/whaemoji.py' from the official
# Unicode list emoji.
#



"""
Automatically generate the file './libs/whaemoji.py' from the official
Unicode list emoji.
"""



import os
import sys
import time
from urllib.request import urlopen



# Source of the Unicode emoji list.
UNICODE_EMOJI_URL = "https://unicode.org/Public/emoji/13.0/emoji-test.txt"



# Generate a Pyhton list with emoji codes from the Unicode emoji list.
unicode_emoji_file = urlopen(UNICODE_EMOJI_URL)
emoji_codes = ""
for emoji_line in unicode_emoji_file:
    emoji_line = emoji_line.decode('utf-8')
    emoji_code_str = emoji_line.split('#')[0].split(';')[0].strip(' \n\r')
    if emoji_code_str:
        emoji_code = emoji_code_str.split(" ")
        emoji_codes += "    u'"
        for code in emoji_code:
            emoji_codes += "\\U{0:08X}".format(int(code, 16))
        emoji_codes += "',\n"



# Assemble the content of the file './libs/whaemoji.py'.
whaemoji = """\
#!/usr/bin/env python3
#
# File: whaemoji.py
# Auth: Joe Broesele
# Mod.: Joe Broesele
# Date: 18 May 2020
# Rev.: """ + time.strftime("%d %b %Y, %H:%M:%S", time.localtime()) + """
#
# This file contains a list of valid Unicode emoji used by the WhatsApp Parser.
#
# It was automatically generated by '""" + os.path.basename(__file__) + """' from this source:
# '""" + UNICODE_EMOJI_URL + """'
#

WHA_EMOJI = [
""" + emoji_codes + """]

"""



# Write the './libs/whaemoji.py' file.
whaemoji_py = os.path.relpath(os.path.join(os.path.dirname(__file__), '../libs', 'whaemoji.py'))
if os.path.exists(whaemoji_py):
    print("WARNING: The file '" + whaemoji_py + "' already exists! Overwrite it (y/n)? ", end='', flush=True)
    for line in sys.stdin:
        if line[0].lower() == "y":
            break
        elif line[0].lower() == "n":
            print("\nSkipped writing to file '" + whaemoji_py + "'.")
            sys.exit(1)
        else:
            print("Please enter 'y' or 'n'. ", end='', flush=True)
try:
    with open(whaemoji_py, 'wt') as whaemoji_py_file:
        whaemoji_py_file.write(whaemoji)
    print("\nThe file '" + whaemoji_py + "' was successfully written.")
except Exception as e:
    print("\nERROR writing to file '" + whaemoji_py + "': " + str(e))
    sys.exit(1)

